spring:
  application:
    name: service-presence
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/db_presence?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:ecopria}
    password: ${SPRING_DATASOURCE_PASSWORD:ecopria_pass_2026}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    listener:
      auto-startup: false
    admin:
      fail-fast: false
    consumer:
      group-id: service-presence
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ecopria.presence.kafka.InscriptionConfirmeeEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8085

service:
  action:
    url: ${SERVICE_ACTION_URL:http://localhost:9090}