server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

service:
  presence:
    url: http://service-presence-backend:8085

spring:
  datasource:
    url: jdbc:mysql://mysql-action:3306/db_action?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ecopria
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:9092
