# mvn spring-boot:run -Dspring-boot.run.profiles=local
# Prérequis : docker compose -f docker-compose.infra.yml up -d

spring:
  kafka:
    bootstrap-servers: localhost:29092
    listener:
      auto-startup: true
    consumer:
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.LinkedHashMap

service:
  action:
    url: http://localhost:9090
  utilisateur:
    url: http://localhost:8082
  presence:
    url: http://localhost:8085
