spring:
  datasource:
    url: jdbc:mysql://mysql-inscription:3306/db_inscription
    username: ecopria
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: service-inscription
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

service:
  action:
    url: http://service-action-backend:9090