server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

spring:
  application:
    name: service-auth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3316/db_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:ecopria}
    password: ${SPRING_DATASOURCE_PASSWORD:ecopria_pass_2026}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    listener:
      auto-startup: true  # ACTIVÉ pour écouter les événements Kafka
    admin:
      fail-fast: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: EcopriaProject2026SecretKeyForJwtTokenSigning
  expiration: 86400000
  refresh-expiration: 604800000

admin:
  verification-url: http://localhost:8088/api/admin/verifications
