# backend/service-utilisateur/src/main/resources/application.yml

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

spring:
  application:
    name: service-utilisateur

  datasource:
    url: jdbc:mysql://mysql-utilisateur:3306/db_utilisateur?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ecopria
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:ecopria_pass_2026}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # crée les tables automatiquement
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: utilisateur-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.Map
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
