server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

spring:
  application:
    name: service-admin

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3312/db_admin?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:ecopria}
    password: ${SPRING_DATASOURCE_PASSWORD:ecopria_pass_2026}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    listener:
      auto-startup: true  # ACTIVÉ pour écouter les événements Kafka
    admin:
      fail-fast: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: EcopriaProject2026SecretKeyForJwtTokenSigning
  expiration: 86400000
  refresh-expiration: 604800000

services:
  auth-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  action-url: ${ACTION_SERVICE_URL:http://localhost:9090}
  inscription-url: ${INSCRIPTION_SERVICE_URL:http://localhost:8080}
  recompense-url: ${RECOMPENSE_SERVICE_URL:http://localhost:8080}
  utilisateur-url: ${UTILISATEUR_SERVICE_URL:http://localhost:8080}