# mvn spring-boot:run -Dspring-boot.run.profiles=local
# Charger .env à la racine : EMAIL_USERNAME, EMAIL_PASSWORD (mot de passe d'application Gmail)
spring:
  kafka:
    bootstrap-servers: localhost:29092
    listener:
      auto-startup: true

ecopria:
  internal:
    auth-base-url: http://localhost:8081
    utilisateur-base-url: http://localhost:8082
    inscription-base-url: http://localhost:8084
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
