@startuml service-presence
title Service Présence — Cas d'utilisation
left to right direction
skinparam packageStyle rectangle

actor Citoyen as CIT
actor Association as ASSO

rectangle "service-presence" {

  package "Présence" {
    usecase "Scanner QR code" as UC1
    usecase "Valider avec PIN" as UC2
    usecase "Afficher QR & PIN" as UC3
    usecase "Voir les présences" as UC4
  }
}

CIT --> UC1
ASSO --> UC2
ASSO --> UC3
ASSO --> UC4

@enduml
